pipeline {

    agent any
    stages {

        stage('Checkout Codebase'){
            steps{
                sh 'ls -lha'
                cleanWs()
                
            }
        }

        stage('Build'){
            steps{
                sh 'ls -lha'
                checkout scm
                sh 'ls -lha'
            }
        }

        stage('Test'){
            steps{
                sh 'echo testing'
            }
        }

        stage('Deploy'){
            steps{
                sh 'echo testing' 
            }
        }
    }

}
