pipeline {

    agent any
    stages {

        stage('Checkout Codebase'){
            steps{
                cleanWs()
                checkout scm: [$class: 'GitSCM', branches: [[name: '*/mark-test']],userRemoteConfigs:
                [[credentialsId: 'Tools-of-software-projects--Cookaholic', url: 'git@github.com:kapchx/Tools-of-software-projects--Cookaholic']]]
            }
        }

        stage('Build'){
            steps{
                sh 'ls -lha'
            }
        }

        stage('Test'){
            steps{
                sh 'echo testing'
            }
        }

        stage('Deploy'){
            steps{
                sh 'echo testing' 
            }
        }
    }

}
